name: Generate static index

on:
  push:
    paths:
      - 'index.html'
      - 'index_template.html'
      - 'soundon.xml'
      - 'apple.json'
      - 'scripts/**'
      - '.github/workflows/generate-index.yml'
  pull_request:
    paths:
      - 'index.html'
      - 'index_template.html'
      - 'soundon.xml'
      - 'apple.json'
      - 'scripts/**'
      - '.github/workflows/generate-index.yml'
  workflow_dispatch:

permissions:
  contents: write  # 需要寫入權限才能自動 commit & push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate index.html
        run: python scripts/generate_index.py

      # PR 情境只做驗證，不做自動提交
      - name: Verify generated file is up to date (PR only)
        if: github.event_name == 'pull_request'
        run: |
          if ! git diff --exit-code index.html; then
            echo 'index.html is not up to date. Run python scripts/generate_index.py and commit the result.' >&2
            exit 1
          fi

      # 非 PR：若有變更，自動提交
      - name: Auto commit changes (non-PR)
        if: github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate index.html [skip ci]"
          file_pattern: index.html
          # 可選：指定作者（預設會用 github-actions[bot]）
          # commit_user_name: "github-actions[bot]"
          # commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
